package org.brisskit.i2b2.webapp.model;

// default package
// Generated 25-Jan-2015 14:11:32 by Hibernate Tools 3.2.0.beta8

import java.util.Date;

/**
 * ConceptDimension generated by hbm2java
 */
public class ConceptDimension implements java.io.Serializable {

	// Fields    

	public String concept_path;

	public String concept_cd;

	public String name_char;

	// Constructors

	/** default constructor */
	public ConceptDimension() {
	}

	public String getConcept_path() {
		return concept_path;
	}

	public void setConcept_path(String concept_path) {
		this.concept_path = concept_path;
	}

	public String getConcept_cd() {
		return concept_cd;
	}

	public void setConcept_cd(String concept_cd) {
		this.concept_cd = concept_cd;
	}

	public String getName_char() {
		return name_char;
	}

	public void setName_char(String name_char) {
		this.name_char = name_char;
	}

	
}
