package org.brisskit.i2b2.webapp.model;

// default package
// Generated 25-Jan-2015 14:11:32 by Hibernate Tools 3.2.0.beta8

import java.util.Date;

/**
 * ObservationFactId generated by hbm2java
 */
public class ObservationFactId implements java.io.Serializable {

	// Fields    

	private int patientNum;

	private String conceptCd;

	private String modifierCd;

	private Date startDate;

	private int encounterNum;

	private int instanceNum;

	private String providerId;

	// Constructors

	/** default constructor */
	public ObservationFactId() {
	}

	/** full constructor */
	public ObservationFactId(int patientNum, String conceptCd,
			String modifierCd, Date startDate, int encounterNum,
			int instanceNum, String providerId) {
		this.patientNum = patientNum;
		this.conceptCd = conceptCd;
		this.modifierCd = modifierCd;
		this.startDate = startDate;
		this.encounterNum = encounterNum;
		this.instanceNum = instanceNum;
		this.providerId = providerId;
	}

	// Property accessors
	public int getPatientNum() {
		return this.patientNum;
	}

	public void setPatientNum(int patientNum) {
		this.patientNum = patientNum;
	}

	public String getConceptCd() {
		return this.conceptCd;
	}

	public void setConceptCd(String conceptCd) {
		this.conceptCd = conceptCd;
	}

	public String getModifierCd() {
		return this.modifierCd;
	}

	public void setModifierCd(String modifierCd) {
		this.modifierCd = modifierCd;
	}

	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	public int getEncounterNum() {
		return this.encounterNum;
	}

	public void setEncounterNum(int encounterNum) {
		this.encounterNum = encounterNum;
	}

	public int getInstanceNum() {
		return this.instanceNum;
	}

	public void setInstanceNum(int instanceNum) {
		this.instanceNum = instanceNum;
	}

	public String getProviderId() {
		return this.providerId;
	}

	public void setProviderId(String providerId) {
		this.providerId = providerId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ObservationFactId))
			return false;
		ObservationFactId castOther = (ObservationFactId) other;

		return (this.getPatientNum() == castOther.getPatientNum())
				&& ((this.getConceptCd() == castOther.getConceptCd()) || (this
						.getConceptCd() != null
						&& castOther.getConceptCd() != null && this
						.getConceptCd().equals(castOther.getConceptCd())))
				&& ((this.getModifierCd() == castOther.getModifierCd()) || (this
						.getModifierCd() != null
						&& castOther.getModifierCd() != null && this
						.getModifierCd().equals(castOther.getModifierCd())))
				&& ((this.getStartDate() == castOther.getStartDate()) || (this
						.getStartDate() != null
						&& castOther.getStartDate() != null && this
						.getStartDate().equals(castOther.getStartDate())))
				&& (this.getEncounterNum() == castOther.getEncounterNum())
				&& (this.getInstanceNum() == castOther.getInstanceNum())
				&& ((this.getProviderId() == castOther.getProviderId()) || (this
						.getProviderId() != null
						&& castOther.getProviderId() != null && this
						.getProviderId().equals(castOther.getProviderId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getPatientNum();
		result = 37 * result
				+ (getConceptCd() == null ? 0 : this.getConceptCd().hashCode());
		result = 37
				* result
				+ (getModifierCd() == null ? 0 : this.getModifierCd()
						.hashCode());
		result = 37 * result
				+ (getStartDate() == null ? 0 : this.getStartDate().hashCode());
		result = 37 * result + this.getEncounterNum();
		result = 37 * result + this.getInstanceNum();
		result = 37
				* result
				+ (getProviderId() == null ? 0 : this.getProviderId()
						.hashCode());
		return result;
	}

}
