package org.brisskit.i2b2.webapp.model;

// default package
// Generated 25-Jan-2015 14:11:32 by Hibernate Tools 3.2.0.beta8

import java.math.BigDecimal;
import java.util.Date;

/**
 * ObservationFact generated by hbm2java
 */
public class ObservationFact implements java.io.Serializable {

	// Fields    

	
	public String patient_ide;
	public int encounter_num;
	public int patient_num;
	public String concept_cd;
	public String valtype_cd;
	public String tval_char;
	public BigDecimal nval_num;

	// Constructors

	/** default constructor */
	public ObservationFact() {
	}

	/** minimal constructor */
/*	public ObservationFact(ObservationFactId id, int textSearchIndex) {
		this.id = id;
		this.textSearchIndex = textSearchIndex;
	}
*/

	/** full constructor */
	public ObservationFact(int encounter_num) {
		//this.id = id;
		this.encounter_num = encounter_num;
	}

		public int getEncounter_num() {
			return this.encounter_num;
		}

		public void setEncounter_num(int encounter_num) {
			this.encounter_num = encounter_num;
		}

		public int getPatient_num() {
			return patient_num;
		}

		public void setPatient_num(int patient_num) {
			this.patient_num = patient_num;
		}

		public String getConcept_cd() {
			return concept_cd;
		}

		public void setConcept_cd(String concept_cd) {
			this.concept_cd = concept_cd;
		}

		public String getValtype_cd() {
			return valtype_cd;
		}

		public void setValtype_cd(String valtype_cd) {
			this.valtype_cd = valtype_cd;
		}

		public String getTval_char() {
			return tval_char;
		}

		public void setTval_char(String tval_char) {
			this.tval_char = tval_char;
		}

		public BigDecimal getNval_num() {
			return nval_num;
		}

		public void setNval_num(BigDecimal nval_num) {
			this.nval_num = nval_num;
		}

		public String getPatient_ide() {
			return patient_ide;
		}

		public void setPatient_ide(String patient_ide) {
			this.patient_ide = patient_ide;
		}
		
}
