package org.brisskit.i2b2.webapp.model;

// default package
// Generated 25-Jan-2015 14:11:32 by Hibernate Tools 3.2.0.beta8

import java.math.BigDecimal;
import java.util.Date;

/**
 * ObservationFact generated by hbm2java
 */
public class ObservationFactFull implements java.io.Serializable {

	// Fields    
	public int encounter_num;
	public int patient_num;
	public String concept_cd;
	public String provider_id;
	public Date start_date;
	public String modifier_cd;
	public int instance_num;
	public String valtype_cd;
	public String tval_char;
	public BigDecimal nval_num;
	public String valueflag_cd;
	public BigDecimal quantity_num;
	public String units_cd;
	public Date end_date;
	public String location_cd;
	public String observation_blob;
	public BigDecimal confidence_num;
	public Date update_date;
	public Date download_date;
	public Date import_date;
	public String sourcesystem_cd;
	public Integer upload_id;
	public int text_search_index;
	public int getEncounter_num() {
		return encounter_num;
	}
	public void setEncounter_num(int encounter_num) {
		this.encounter_num = encounter_num;
	}
	public int getPatient_num() {
		return patient_num;
	}
	public void setPatient_num(int patient_num) {
		this.patient_num = patient_num;
	}
	public String getConcept_cd() {
		return concept_cd;
	}
	public void setConcept_cd(String concept_cd) {
		this.concept_cd = concept_cd;
	}
	public String getProvider_id() {
		return provider_id;
	}
	public void setProvider_id(String provider_id) {
		this.provider_id = provider_id;
	}
	public Date getStart_date() {
		return start_date;
	}
	public void setStart_date(Date start_date) {
		this.start_date = start_date;
	}
	public String getModifier_cd() {
		return modifier_cd;
	}
	public void setModifier_cd(String modifier_cd) {
		this.modifier_cd = modifier_cd;
	}
	public int getInstance_num() {
		return instance_num;
	}
	public void setInstance_num(int instance_num) {
		this.instance_num = instance_num;
	}
	public String getValtype_cd() {
		return valtype_cd;
	}
	public void setValtype_cd(String valtype_cd) {
		this.valtype_cd = valtype_cd;
	}
	public String getTval_char() {
		return tval_char;
	}
	public void setTval_char(String tval_char) {
		this.tval_char = tval_char;
	}
	public BigDecimal getNval_num() {
		return nval_num;
	}
	public void setNval_num(BigDecimal nval_num) {
		this.nval_num = nval_num;
	}
	public String getValueflag_cd() {
		return valueflag_cd;
	}
	public void setValueflag_cd(String valueflag_cd) {
		this.valueflag_cd = valueflag_cd;
	}
	public BigDecimal getQuantity_num() {
		return quantity_num;
	}
	public void setQuantity_num(BigDecimal quantity_num) {
		this.quantity_num = quantity_num;
	}
	public String getUnits_cd() {
		return units_cd;
	}
	public void setUnits_cd(String units_cd) {
		this.units_cd = units_cd;
	}
	public Date getEnd_date() {
		return end_date;
	}
	public void setEnd_date(Date end_date) {
		this.end_date = end_date;
	}
	public String getLocation_cd() {
		return location_cd;
	}
	public void setLocation_cd(String location_cd) {
		this.location_cd = location_cd;
	}
	public String getObservation_blob() {
		return observation_blob;
	}
	public void setObservation_blob(String observation_blob) {
		this.observation_blob = observation_blob;
	}
	public BigDecimal getConfidence_num() {
		return confidence_num;
	}
	public void setConfidence_num(BigDecimal confidence_num) {
		this.confidence_num = confidence_num;
	}
	public Date getUpdate_date() {
		return update_date;
	}
	public void setUpdate_date(Date update_date) {
		this.update_date = update_date;
	}
	public Date getDownload_date() {
		return download_date;
	}
	public void setDownload_date(Date download_date) {
		this.download_date = download_date;
	}
	public Date getImport_date() {
		return import_date;
	}
	public void setImport_date(Date import_date) {
		this.import_date = import_date;
	}
	public String getSourcesystem_cd() {
		return sourcesystem_cd;
	}
	public void setSourcesystem_cd(String sourcesystem_cd) {
		this.sourcesystem_cd = sourcesystem_cd;
	}
	public Integer getUpload_id() {
		return upload_id;
	}
	public void setUpload_id(Integer upload_id) {
		this.upload_id = upload_id;
	}
	public int getText_search_index() {
		return text_search_index;
	}
	public void setText_search_index(int text_search_index) {
		this.text_search_index = text_search_index;
	}

	
	
	
}
