package org.brisskit.i2b2.webapp.model;

// default package
// Generated 25-Jan-2015 14:11:32 by Hibernate Tools 3.2.0.beta8

import java.math.BigDecimal;
import java.util.Date;

/**
 * ObservationFact generated by hbm2java
 */
public class ObservationFactO implements java.io.Serializable {

	// Fields    

	public ObservationFactId id;

	public String valtypeCd;

	public String tvalChar;

	public BigDecimal nvalNum;

	public String valueflagCd;

	public BigDecimal quantityNum;

	public String unitsCd;

	public Date endDate;

	public String locationCd;

	public String observationBlob;

	public BigDecimal confidenceNum;

	public Date updateDate;

	public Date downloadDate;

	public Date importDate;

	public String sourcesystemCd;

	public Integer uploadId;

	public int textSearchIndex;

	// Constructors

	/** default constructor */
	public ObservationFactO() {
	}

	/** minimal constructor */
	public ObservationFactO(ObservationFactId id, int textSearchIndex) {
		this.id = id;
		this.textSearchIndex = textSearchIndex;
	}

	/** full constructor */
	public ObservationFactO(ObservationFactId id, String valtypeCd,
			String tvalChar, BigDecimal nvalNum, String valueflagCd,
			BigDecimal quantityNum, String unitsCd, Date endDate,
			String locationCd, String observationBlob,
			BigDecimal confidenceNum, Date updateDate, Date downloadDate,
			Date importDate, String sourcesystemCd, Integer uploadId,
			int textSearchIndex) {
		this.id = id;
		this.valtypeCd = valtypeCd;
		this.tvalChar = tvalChar;
		this.nvalNum = nvalNum;
		this.valueflagCd = valueflagCd;
		this.quantityNum = quantityNum;
		this.unitsCd = unitsCd;
		this.endDate = endDate;
		this.locationCd = locationCd;
		this.observationBlob = observationBlob;
		this.confidenceNum = confidenceNum;
		this.updateDate = updateDate;
		this.downloadDate = downloadDate;
		this.importDate = importDate;
		this.sourcesystemCd = sourcesystemCd;
		this.uploadId = uploadId;
		this.textSearchIndex = textSearchIndex;
	}

	// Property accessors
	public ObservationFactId getId() {
		return this.id;
	}

	public void setId(ObservationFactId id) {
		this.id = id;
	}

	public String getValtypeCd() {
		return this.valtypeCd;
	}

	public void setValtypeCd(String valtypeCd) {
		this.valtypeCd = valtypeCd;
	}

	public String getTvalChar() {
		return this.tvalChar;
	}

	public void setTvalChar(String tvalChar) {
		this.tvalChar = tvalChar;
	}

	public BigDecimal getNvalNum() {
		return this.nvalNum;
	}

	public void setNvalNum(BigDecimal nvalNum) {
		this.nvalNum = nvalNum;
	}

	public String getValueflagCd() {
		return this.valueflagCd;
	}

	public void setValueflagCd(String valueflagCd) {
		this.valueflagCd = valueflagCd;
	}

	public BigDecimal getQuantityNum() {
		return this.quantityNum;
	}

	public void setQuantityNum(BigDecimal quantityNum) {
		this.quantityNum = quantityNum;
	}

	public String getUnitsCd() {
		return this.unitsCd;
	}

	public void setUnitsCd(String unitsCd) {
		this.unitsCd = unitsCd;
	}

	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public String getLocationCd() {
		return this.locationCd;
	}

	public void setLocationCd(String locationCd) {
		this.locationCd = locationCd;
	}

	public String getObservationBlob() {
		return this.observationBlob;
	}

	public void setObservationBlob(String observationBlob) {
		this.observationBlob = observationBlob;
	}

	public BigDecimal getConfidenceNum() {
		return this.confidenceNum;
	}

	public void setConfidenceNum(BigDecimal confidenceNum) {
		this.confidenceNum = confidenceNum;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	public Date getDownloadDate() {
		return this.downloadDate;
	}

	public void setDownloadDate(Date downloadDate) {
		this.downloadDate = downloadDate;
	}

	public Date getImportDate() {
		return this.importDate;
	}

	public void setImportDate(Date importDate) {
		this.importDate = importDate;
	}

	public String getSourcesystemCd() {
		return this.sourcesystemCd;
	}

	public void setSourcesystemCd(String sourcesystemCd) {
		this.sourcesystemCd = sourcesystemCd;
	}

	public Integer getUploadId() {
		return this.uploadId;
	}

	public void setUploadId(Integer uploadId) {
		this.uploadId = uploadId;
	}

	public int getTextSearchIndex() {
		return this.textSearchIndex;
	}

	public void setTextSearchIndex(int textSearchIndex) {
		this.textSearchIndex = textSearchIndex;
	}

}
