package org.brisskit.i2b2.webapp.model;

import java.util.Date;

// default package
// Generated 25-Jan-2015 14:11:32 by Hibernate Tools 3.2.0.beta8

/**
 * Shajid generated by hbm2java
 */
public class Ontology implements java.io.Serializable {

	// Fields    
	public int c_hlevel;

	public String c_fullname;

	public String c_name;

	public char c_synonym_cd;

	public String c_visualattributes;

	public Integer c_totalnum;

	public String c_basecode;

	public String c_metadataxml;

	public String c_facttablecolumn;

	public String c_tablename;

	public String c_columnname;

	public String c_columndatatype;

	public String c_operator;

	public String c_dimcode;

	public String c_comment;

	public String c_tooltip;
	
	public String getM_applied_path() {
		return m_applied_path;
	}

	public void setM_applied_path(String m_applied_path) {
		this.m_applied_path = m_applied_path;
	}

	public Date getUpdate_date() {
		return update_date;
	}

	public void setUpdate_date(Date update_date) {
		this.update_date = update_date;
	}

	public Date getDownload_date() {
		return download_date;
	}

	public void setDownload_date(Date download_date) {
		this.download_date = download_date;
	}

	public Date getImport_date() {
		return import_date;
	}

	public void setImport_date(Date import_date) {
		this.import_date = import_date;
	}

	public String getSourcesystem_cd() {
		return sourcesystem_cd;
	}

	public void setSourcesystem_cd(String sourcesystem_cd) {
		this.sourcesystem_cd = sourcesystem_cd;
	}

	public String m_applied_path;

	public Date update_date;

	public Date download_date;

	public Date import_date;

	public String sourcesystem_cd;


	// Constructors

	/** default constructor */
	public Ontology() {
	}

	public int getC_hlevel() {
		return c_hlevel;
	}

	public void setC_hlevel(int c_hlevel) {
		this.c_hlevel = c_hlevel;
	}

	public String getC_fullname() {
		return c_fullname;
	}

	public void setC_fullname(String c_fullname) {
		this.c_fullname = c_fullname;
	}

	public String getC_name() {
		return c_name;
	}

	public void setC_name(String c_name) {
		this.c_name = c_name;
	}

	public char getC_synonym_cd() {
		return c_synonym_cd;
	}

	public void setC_synonym_cd(char c_synonym_cd) {
		this.c_synonym_cd = c_synonym_cd;
	}

	public String getC_visualattributes() {
		return c_visualattributes;
	}

	public void setC_visualattributes(String c_visualattributes) {
		this.c_visualattributes = c_visualattributes;
	}

	public Integer getC_totalnum() {
		return c_totalnum;
	}

	public void setC_totalnum(Integer c_totalnum) {
		this.c_totalnum = c_totalnum;
	}

	public String getC_basecode() {
		return c_basecode;
	}

	public void setC_basecode(String c_basecode) {
		this.c_basecode = c_basecode;
	}

	public String getC_metadataxml() {
		return c_metadataxml;
	}

	public void setC_metadataxml(String c_metadataxml) {
		this.c_metadataxml = c_metadataxml;
	}

	public String getC_facttablecolumn() {
		return c_facttablecolumn;
	}

	public void setC_facttablecolumn(String c_facttablecolumn) {
		this.c_facttablecolumn = c_facttablecolumn;
	}

	public String getC_tablename() {
		return c_tablename;
	}

	public void setC_tablename(String c_tablename) {
		this.c_tablename = c_tablename;
	}

	public String getC_columnname() {
		return c_columnname;
	}

	public void setC_columnname(String c_columnname) {
		this.c_columnname = c_columnname;
	}

	public String getC_columndatatype() {
		return c_columndatatype;
	}

	public void setC_columndatatype(String c_columndatatype) {
		this.c_columndatatype = c_columndatatype;
	}

	public String getC_operator() {
		return c_operator;
	}

	public void setC_operator(String c_operator) {
		this.c_operator = c_operator;
	}

	public String getC_dimcode() {
		return c_dimcode;
	}

	public void setC_dimcode(String c_dimcode) {
		this.c_dimcode = c_dimcode;
	}

	public String getC_comment() {
		return c_comment;
	}

	public void setC_comment(String c_comment) {
		this.c_comment = c_comment;
	}

	public String getC_tooltip() {
		return c_tooltip;
	}

	public void setC_tooltip(String c_tooltip) {
		this.c_tooltip = c_tooltip;
	}

	
}
