package org.brisskit.i2b2.webapp.model;

// default package
// Generated 25-Jan-2015 14:11:32 by Hibernate Tools 3.2.0.beta8

import java.util.Date;

/**
 * PatientDimension generated by hbm2java
 */
public class PatientDimension implements java.io.Serializable {

	// Fields    

	private int patientNum;

	private String vitalStatusCd;

	private Date birthDate;

	private Date deathDate;

	private String sexCd;

	private Integer ageInYearsNum;

	private String languageCd;

	private String raceCd;

	private String maritalStatusCd;

	private String religionCd;

	private String zipCd;

	private String statecityzipPath;

	private String incomeCd;

	private String patientBlob;

	private Date updateDate;

	private Date downloadDate;

	private Date importDate;

	private String sourcesystemCd;

	private Integer uploadId;

	// Constructors

	/** default constructor */
	public PatientDimension() {
	}

	/** minimal constructor */
	public PatientDimension(int patientNum) {
		this.patientNum = patientNum;
	}

	/** full constructor */
	public PatientDimension(int patientNum, String vitalStatusCd,
			Date birthDate, Date deathDate, String sexCd,
			Integer ageInYearsNum, String languageCd, String raceCd,
			String maritalStatusCd, String religionCd, String zipCd,
			String statecityzipPath, String incomeCd, String patientBlob,
			Date updateDate, Date downloadDate, Date importDate,
			String sourcesystemCd, Integer uploadId) {
		this.patientNum = patientNum;
		this.vitalStatusCd = vitalStatusCd;
		this.birthDate = birthDate;
		this.deathDate = deathDate;
		this.sexCd = sexCd;
		this.ageInYearsNum = ageInYearsNum;
		this.languageCd = languageCd;
		this.raceCd = raceCd;
		this.maritalStatusCd = maritalStatusCd;
		this.religionCd = religionCd;
		this.zipCd = zipCd;
		this.statecityzipPath = statecityzipPath;
		this.incomeCd = incomeCd;
		this.patientBlob = patientBlob;
		this.updateDate = updateDate;
		this.downloadDate = downloadDate;
		this.importDate = importDate;
		this.sourcesystemCd = sourcesystemCd;
		this.uploadId = uploadId;
	}

	// Property accessors
	public int getPatientNum() {
		return this.patientNum;
	}

	public void setPatientNum(int patientNum) {
		this.patientNum = patientNum;
	}

	public String getVitalStatusCd() {
		return this.vitalStatusCd;
	}

	public void setVitalStatusCd(String vitalStatusCd) {
		this.vitalStatusCd = vitalStatusCd;
	}

	public Date getBirthDate() {
		return this.birthDate;
	}

	public void setBirthDate(Date birthDate) {
		this.birthDate = birthDate;
	}

	public Date getDeathDate() {
		return this.deathDate;
	}

	public void setDeathDate(Date deathDate) {
		this.deathDate = deathDate;
	}

	public String getSexCd() {
		return this.sexCd;
	}

	public void setSexCd(String sexCd) {
		this.sexCd = sexCd;
	}

	public Integer getAgeInYearsNum() {
		return this.ageInYearsNum;
	}

	public void setAgeInYearsNum(Integer ageInYearsNum) {
		this.ageInYearsNum = ageInYearsNum;
	}

	public String getLanguageCd() {
		return this.languageCd;
	}

	public void setLanguageCd(String languageCd) {
		this.languageCd = languageCd;
	}

	public String getRaceCd() {
		return this.raceCd;
	}

	public void setRaceCd(String raceCd) {
		this.raceCd = raceCd;
	}

	public String getMaritalStatusCd() {
		return this.maritalStatusCd;
	}

	public void setMaritalStatusCd(String maritalStatusCd) {
		this.maritalStatusCd = maritalStatusCd;
	}

	public String getReligionCd() {
		return this.religionCd;
	}

	public void setReligionCd(String religionCd) {
		this.religionCd = religionCd;
	}

	public String getZipCd() {
		return this.zipCd;
	}

	public void setZipCd(String zipCd) {
		this.zipCd = zipCd;
	}

	public String getStatecityzipPath() {
		return this.statecityzipPath;
	}

	public void setStatecityzipPath(String statecityzipPath) {
		this.statecityzipPath = statecityzipPath;
	}

	public String getIncomeCd() {
		return this.incomeCd;
	}

	public void setIncomeCd(String incomeCd) {
		this.incomeCd = incomeCd;
	}

	public String getPatientBlob() {
		return this.patientBlob;
	}

	public void setPatientBlob(String patientBlob) {
		this.patientBlob = patientBlob;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	public Date getDownloadDate() {
		return this.downloadDate;
	}

	public void setDownloadDate(Date downloadDate) {
		this.downloadDate = downloadDate;
	}

	public Date getImportDate() {
		return this.importDate;
	}

	public void setImportDate(Date importDate) {
		this.importDate = importDate;
	}

	public String getSourcesystemCd() {
		return this.sourcesystemCd;
	}

	public void setSourcesystemCd(String sourcesystemCd) {
		this.sourcesystemCd = sourcesystemCd;
	}

	public Integer getUploadId() {
		return this.uploadId;
	}

	public void setUploadId(Integer uploadId) {
		this.uploadId = uploadId;
	}

}
