package org.brisskit.i2b2.webapp.model;

// default package
// Generated 25-Jan-2015 14:11:32 by Hibernate Tools 3.2.0.beta8

/**
 * PatientMappingId generated by hbm2java
 */
public class PatientMappingId implements java.io.Serializable {

	// Fields    

	private String patientIde;

	private String patientIdeSource;

	private String projectId;

	// Constructors

	/** default constructor */
	public PatientMappingId() {
	}

	/** full constructor */
	public PatientMappingId(String patientIde, String patientIdeSource,
			String projectId) {
		this.patientIde = patientIde;
		this.patientIdeSource = patientIdeSource;
		this.projectId = projectId;
	}

	// Property accessors
	public String getPatientIde() {
		return this.patientIde;
	}

	public void setPatientIde(String patientIde) {
		this.patientIde = patientIde;
	}

	public String getPatientIdeSource() {
		return this.patientIdeSource;
	}

	public void setPatientIdeSource(String patientIdeSource) {
		this.patientIdeSource = patientIdeSource;
	}

	public String getProjectId() {
		return this.projectId;
	}

	public void setProjectId(String projectId) {
		this.projectId = projectId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PatientMappingId))
			return false;
		PatientMappingId castOther = (PatientMappingId) other;

		return ((this.getPatientIde() == castOther.getPatientIde()) || (this
				.getPatientIde() != null
				&& castOther.getPatientIde() != null && this.getPatientIde()
				.equals(castOther.getPatientIde())))
				&& ((this.getPatientIdeSource() == castOther
						.getPatientIdeSource()) || (this.getPatientIdeSource() != null
						&& castOther.getPatientIdeSource() != null && this
						.getPatientIdeSource().equals(
								castOther.getPatientIdeSource())))
				&& ((this.getProjectId() == castOther.getProjectId()) || (this
						.getProjectId() != null
						&& castOther.getProjectId() != null && this
						.getProjectId().equals(castOther.getProjectId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getPatientIde() == null ? 0 : this.getPatientIde()
						.hashCode());
		result = 37
				* result
				+ (getPatientIdeSource() == null ? 0 : this
						.getPatientIdeSource().hashCode());
		result = 37 * result
				+ (getProjectId() == null ? 0 : this.getProjectId().hashCode());
		return result;
	}

}
