package org.brisskit.i2b2.webapp.model;

// default package
// Generated 25-Jan-2015 14:11:32 by Hibernate Tools 3.2.0.beta8

import java.util.Date;

/**
 * PatientMapping generated by hbm2java
 */
public class PatientMapping implements java.io.Serializable {

	// Fields    

        public String patient_ide;
        
        public int patient_num;
        
	
	// Constructors

	/** default constructor */
	public PatientMapping() {
	}


	public String getPatient_ide() {
		return patient_ide;
	}


	public void setPatient_ide(String patient_ide) {
		this.patient_ide = patient_ide;
	}


	public int getPatient_num() {
		return patient_num;
	}


	public void setPatient_num(int patient_num) {
		this.patient_num = patient_num;
	}

	
	// Property accessors

}
