package org.brisskit.i2b2.webapp.model;

// default package
// Generated 25-Jan-2015 14:11:32 by Hibernate Tools 3.2.0.beta8

import java.util.Date;

/**
 * ShajidId generated by hbm2java
 */
public class ShajidId implements java.io.Serializable {

	// Fields    

	private int CHlevel;

	private String CFullname;

	private String CName;

	private char CSynonymCd;

	private String CVisualattributes;

	private Integer CTotalnum;

	private String CBasecode;

	private String CMetadataxml;

	private String CFacttablecolumn;

	private String CTablename;

	private String CColumnname;

	private String CColumndatatype;

	private String COperator;

	private String CDimcode;

	private String CComment;

	private String CTooltip;

	private String MAppliedPath;

	private Date updateDate;

	private Date downloadDate;

	private Date importDate;

	private String sourcesystemCd;

	private String valuetypeCd;

	private String MExclusionCd;

	private String CPath;

	private String CSymbol;

	// Constructors

	/** default constructor */
	public ShajidId() {
	}

	/** minimal constructor */
	public ShajidId(int CHlevel, String CFullname, String CName,
			char CSynonymCd, String CVisualattributes, String CFacttablecolumn,
			String CTablename, String CColumnname, String CColumndatatype,
			String COperator, String CDimcode, String MAppliedPath,
			Date updateDate) {
		this.CHlevel = CHlevel;
		this.CFullname = CFullname;
		this.CName = CName;
		this.CSynonymCd = CSynonymCd;
		this.CVisualattributes = CVisualattributes;
		this.CFacttablecolumn = CFacttablecolumn;
		this.CTablename = CTablename;
		this.CColumnname = CColumnname;
		this.CColumndatatype = CColumndatatype;
		this.COperator = COperator;
		this.CDimcode = CDimcode;
		this.MAppliedPath = MAppliedPath;
		this.updateDate = updateDate;
	}

	/** full constructor */
	public ShajidId(int CHlevel, String CFullname, String CName,
			char CSynonymCd, String CVisualattributes, Integer CTotalnum,
			String CBasecode, String CMetadataxml, String CFacttablecolumn,
			String CTablename, String CColumnname, String CColumndatatype,
			String COperator, String CDimcode, String CComment,
			String CTooltip, String MAppliedPath, Date updateDate,
			Date downloadDate, Date importDate, String sourcesystemCd,
			String valuetypeCd, String MExclusionCd, String CPath,
			String CSymbol) {
		this.CHlevel = CHlevel;
		this.CFullname = CFullname;
		this.CName = CName;
		this.CSynonymCd = CSynonymCd;
		this.CVisualattributes = CVisualattributes;
		this.CTotalnum = CTotalnum;
		this.CBasecode = CBasecode;
		this.CMetadataxml = CMetadataxml;
		this.CFacttablecolumn = CFacttablecolumn;
		this.CTablename = CTablename;
		this.CColumnname = CColumnname;
		this.CColumndatatype = CColumndatatype;
		this.COperator = COperator;
		this.CDimcode = CDimcode;
		this.CComment = CComment;
		this.CTooltip = CTooltip;
		this.MAppliedPath = MAppliedPath;
		this.updateDate = updateDate;
		this.downloadDate = downloadDate;
		this.importDate = importDate;
		this.sourcesystemCd = sourcesystemCd;
		this.valuetypeCd = valuetypeCd;
		this.MExclusionCd = MExclusionCd;
		this.CPath = CPath;
		this.CSymbol = CSymbol;
	}

	// Property accessors
	public int getCHlevel() {
		return this.CHlevel;
	}

	public void setCHlevel(int CHlevel) {
		this.CHlevel = CHlevel;
	}

	public String getCFullname() {
		return this.CFullname;
	}

	public void setCFullname(String CFullname) {
		this.CFullname = CFullname;
	}

	public String getCName() {
		return this.CName;
	}

	public void setCName(String CName) {
		this.CName = CName;
	}

	public char getCSynonymCd() {
		return this.CSynonymCd;
	}

	public void setCSynonymCd(char CSynonymCd) {
		this.CSynonymCd = CSynonymCd;
	}

	public String getCVisualattributes() {
		return this.CVisualattributes;
	}

	public void setCVisualattributes(String CVisualattributes) {
		this.CVisualattributes = CVisualattributes;
	}

	public Integer getCTotalnum() {
		return this.CTotalnum;
	}

	public void setCTotalnum(Integer CTotalnum) {
		this.CTotalnum = CTotalnum;
	}

	public String getCBasecode() {
		return this.CBasecode;
	}

	public void setCBasecode(String CBasecode) {
		this.CBasecode = CBasecode;
	}

	public String getCMetadataxml() {
		return this.CMetadataxml;
	}

	public void setCMetadataxml(String CMetadataxml) {
		this.CMetadataxml = CMetadataxml;
	}

	public String getCFacttablecolumn() {
		return this.CFacttablecolumn;
	}

	public void setCFacttablecolumn(String CFacttablecolumn) {
		this.CFacttablecolumn = CFacttablecolumn;
	}

	public String getCTablename() {
		return this.CTablename;
	}

	public void setCTablename(String CTablename) {
		this.CTablename = CTablename;
	}

	public String getCColumnname() {
		return this.CColumnname;
	}

	public void setCColumnname(String CColumnname) {
		this.CColumnname = CColumnname;
	}

	public String getCColumndatatype() {
		return this.CColumndatatype;
	}

	public void setCColumndatatype(String CColumndatatype) {
		this.CColumndatatype = CColumndatatype;
	}

	public String getCOperator() {
		return this.COperator;
	}

	public void setCOperator(String COperator) {
		this.COperator = COperator;
	}

	public String getCDimcode() {
		return this.CDimcode;
	}

	public void setCDimcode(String CDimcode) {
		this.CDimcode = CDimcode;
	}

	public String getCComment() {
		return this.CComment;
	}

	public void setCComment(String CComment) {
		this.CComment = CComment;
	}

	public String getCTooltip() {
		return this.CTooltip;
	}

	public void setCTooltip(String CTooltip) {
		this.CTooltip = CTooltip;
	}

	public String getMAppliedPath() {
		return this.MAppliedPath;
	}

	public void setMAppliedPath(String MAppliedPath) {
		this.MAppliedPath = MAppliedPath;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	public Date getDownloadDate() {
		return this.downloadDate;
	}

	public void setDownloadDate(Date downloadDate) {
		this.downloadDate = downloadDate;
	}

	public Date getImportDate() {
		return this.importDate;
	}

	public void setImportDate(Date importDate) {
		this.importDate = importDate;
	}

	public String getSourcesystemCd() {
		return this.sourcesystemCd;
	}

	public void setSourcesystemCd(String sourcesystemCd) {
		this.sourcesystemCd = sourcesystemCd;
	}

	public String getValuetypeCd() {
		return this.valuetypeCd;
	}

	public void setValuetypeCd(String valuetypeCd) {
		this.valuetypeCd = valuetypeCd;
	}

	public String getMExclusionCd() {
		return this.MExclusionCd;
	}

	public void setMExclusionCd(String MExclusionCd) {
		this.MExclusionCd = MExclusionCd;
	}

	public String getCPath() {
		return this.CPath;
	}

	public void setCPath(String CPath) {
		this.CPath = CPath;
	}

	public String getCSymbol() {
		return this.CSymbol;
	}

	public void setCSymbol(String CSymbol) {
		this.CSymbol = CSymbol;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ShajidId))
			return false;
		ShajidId castOther = (ShajidId) other;

		return (this.getCHlevel() == castOther.getCHlevel())
				&& ((this.getCFullname() == castOther.getCFullname()) || (this
						.getCFullname() != null
						&& castOther.getCFullname() != null && this
						.getCFullname().equals(castOther.getCFullname())))
				&& ((this.getCName() == castOther.getCName()) || (this
						.getCName() != null
						&& castOther.getCName() != null && this.getCName()
						.equals(castOther.getCName())))
				&& (this.getCSynonymCd() == castOther.getCSynonymCd())
				&& ((this.getCVisualattributes() == castOther
						.getCVisualattributes()) || (this
						.getCVisualattributes() != null
						&& castOther.getCVisualattributes() != null && this
						.getCVisualattributes().equals(
								castOther.getCVisualattributes())))
				&& ((this.getCTotalnum() == castOther.getCTotalnum()) || (this
						.getCTotalnum() != null
						&& castOther.getCTotalnum() != null && this
						.getCTotalnum().equals(castOther.getCTotalnum())))
				&& ((this.getCBasecode() == castOther.getCBasecode()) || (this
						.getCBasecode() != null
						&& castOther.getCBasecode() != null && this
						.getCBasecode().equals(castOther.getCBasecode())))
				&& ((this.getCMetadataxml() == castOther.getCMetadataxml()) || (this
						.getCMetadataxml() != null
						&& castOther.getCMetadataxml() != null && this
						.getCMetadataxml().equals(castOther.getCMetadataxml())))
				&& ((this.getCFacttablecolumn() == castOther
						.getCFacttablecolumn()) || (this.getCFacttablecolumn() != null
						&& castOther.getCFacttablecolumn() != null && this
						.getCFacttablecolumn().equals(
								castOther.getCFacttablecolumn())))
				&& ((this.getCTablename() == castOther.getCTablename()) || (this
						.getCTablename() != null
						&& castOther.getCTablename() != null && this
						.getCTablename().equals(castOther.getCTablename())))
				&& ((this.getCColumnname() == castOther.getCColumnname()) || (this
						.getCColumnname() != null
						&& castOther.getCColumnname() != null && this
						.getCColumnname().equals(castOther.getCColumnname())))
				&& ((this.getCColumndatatype() == castOther
						.getCColumndatatype()) || (this.getCColumndatatype() != null
						&& castOther.getCColumndatatype() != null && this
						.getCColumndatatype().equals(
								castOther.getCColumndatatype())))
				&& ((this.getCOperator() == castOther.getCOperator()) || (this
						.getCOperator() != null
						&& castOther.getCOperator() != null && this
						.getCOperator().equals(castOther.getCOperator())))
				&& ((this.getCDimcode() == castOther.getCDimcode()) || (this
						.getCDimcode() != null
						&& castOther.getCDimcode() != null && this
						.getCDimcode().equals(castOther.getCDimcode())))
				&& ((this.getCComment() == castOther.getCComment()) || (this
						.getCComment() != null
						&& castOther.getCComment() != null && this
						.getCComment().equals(castOther.getCComment())))
				&& ((this.getCTooltip() == castOther.getCTooltip()) || (this
						.getCTooltip() != null
						&& castOther.getCTooltip() != null && this
						.getCTooltip().equals(castOther.getCTooltip())))
				&& ((this.getMAppliedPath() == castOther.getMAppliedPath()) || (this
						.getMAppliedPath() != null
						&& castOther.getMAppliedPath() != null && this
						.getMAppliedPath().equals(castOther.getMAppliedPath())))
				&& ((this.getUpdateDate() == castOther.getUpdateDate()) || (this
						.getUpdateDate() != null
						&& castOther.getUpdateDate() != null && this
						.getUpdateDate().equals(castOther.getUpdateDate())))
				&& ((this.getDownloadDate() == castOther.getDownloadDate()) || (this
						.getDownloadDate() != null
						&& castOther.getDownloadDate() != null && this
						.getDownloadDate().equals(castOther.getDownloadDate())))
				&& ((this.getImportDate() == castOther.getImportDate()) || (this
						.getImportDate() != null
						&& castOther.getImportDate() != null && this
						.getImportDate().equals(castOther.getImportDate())))
				&& ((this.getSourcesystemCd() == castOther.getSourcesystemCd()) || (this
						.getSourcesystemCd() != null
						&& castOther.getSourcesystemCd() != null && this
						.getSourcesystemCd().equals(
								castOther.getSourcesystemCd())))
				&& ((this.getValuetypeCd() == castOther.getValuetypeCd()) || (this
						.getValuetypeCd() != null
						&& castOther.getValuetypeCd() != null && this
						.getValuetypeCd().equals(castOther.getValuetypeCd())))
				&& ((this.getMExclusionCd() == castOther.getMExclusionCd()) || (this
						.getMExclusionCd() != null
						&& castOther.getMExclusionCd() != null && this
						.getMExclusionCd().equals(castOther.getMExclusionCd())))
				&& ((this.getCPath() == castOther.getCPath()) || (this
						.getCPath() != null
						&& castOther.getCPath() != null && this.getCPath()
						.equals(castOther.getCPath())))
				&& ((this.getCSymbol() == castOther.getCSymbol()) || (this
						.getCSymbol() != null
						&& castOther.getCSymbol() != null && this.getCSymbol()
						.equals(castOther.getCSymbol())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCHlevel();
		result = 37 * result
				+ (getCFullname() == null ? 0 : this.getCFullname().hashCode());
		result = 37 * result
				+ (getCName() == null ? 0 : this.getCName().hashCode());
		result = 37 * result + this.getCSynonymCd();
		result = 37
				* result
				+ (getCVisualattributes() == null ? 0 : this
						.getCVisualattributes().hashCode());
		result = 37 * result
				+ (getCTotalnum() == null ? 0 : this.getCTotalnum().hashCode());
		result = 37 * result
				+ (getCBasecode() == null ? 0 : this.getCBasecode().hashCode());
		result = 37
				* result
				+ (getCMetadataxml() == null ? 0 : this.getCMetadataxml()
						.hashCode());
		result = 37
				* result
				+ (getCFacttablecolumn() == null ? 0 : this
						.getCFacttablecolumn().hashCode());
		result = 37
				* result
				+ (getCTablename() == null ? 0 : this.getCTablename()
						.hashCode());
		result = 37
				* result
				+ (getCColumnname() == null ? 0 : this.getCColumnname()
						.hashCode());
		result = 37
				* result
				+ (getCColumndatatype() == null ? 0 : this.getCColumndatatype()
						.hashCode());
		result = 37 * result
				+ (getCOperator() == null ? 0 : this.getCOperator().hashCode());
		result = 37 * result
				+ (getCDimcode() == null ? 0 : this.getCDimcode().hashCode());
		result = 37 * result
				+ (getCComment() == null ? 0 : this.getCComment().hashCode());
		result = 37 * result
				+ (getCTooltip() == null ? 0 : this.getCTooltip().hashCode());
		result = 37
				* result
				+ (getMAppliedPath() == null ? 0 : this.getMAppliedPath()
						.hashCode());
		result = 37
				* result
				+ (getUpdateDate() == null ? 0 : this.getUpdateDate()
						.hashCode());
		result = 37
				* result
				+ (getDownloadDate() == null ? 0 : this.getDownloadDate()
						.hashCode());
		result = 37
				* result
				+ (getImportDate() == null ? 0 : this.getImportDate()
						.hashCode());
		result = 37
				* result
				+ (getSourcesystemCd() == null ? 0 : this.getSourcesystemCd()
						.hashCode());
		result = 37
				* result
				+ (getValuetypeCd() == null ? 0 : this.getValuetypeCd()
						.hashCode());
		result = 37
				* result
				+ (getMExclusionCd() == null ? 0 : this.getMExclusionCd()
						.hashCode());
		result = 37 * result
				+ (getCPath() == null ? 0 : this.getCPath().hashCode());
		result = 37 * result
				+ (getCSymbol() == null ? 0 : this.getCSymbol().hashCode());
		return result;
	}

}
