package org.brisskit.i2b2.webapp.model;

// default package
// Generated 25-Jan-2015 14:11:32 by Hibernate Tools 3.2.0.beta8

/**
 * Shajid generated by hbm2java
 */
public class Shajid implements java.io.Serializable {

	// Fields    

	private ShajidId id;

	// Constructors

	/** default constructor */
	public Shajid() {
	}

	/** full constructor */
	public Shajid(ShajidId id) {
		this.id = id;
	}

	// Property accessors
	public ShajidId getId() {
		return this.id;
	}

	public void setId(ShajidId id) {
		this.id = id;
	}

}
