package org.brisskit.i2b2.webapp.model;

import java.util.Date;

// default package
// Generated 25-Jan-2015 14:11:32 by Hibernate Tools 3.2.0.beta8

/**
 * TableAccess generated by hbm2java
 */
public class TableAccess implements java.io.Serializable {

	// Fields    

	public String c_table_cd;

	public String c_table_name;

	public Character c_protected_access;

	public int c_hlevel;

	public String c_fullname;

	public String c_name;

	public char c_synonym_cd;

	public String c_visualattributes;

	public Integer c_totalnum;

	public String c_basecode;

	public String c_metadataxml;

	public String c_facttablecolumn;

	public String c_dimtablename;

	public String c_columnname;

	public String c_columndatatype;

	public String c_operator;

	public String c_dimcode;

	public String c_comment;

	public String c_tooltip;

	public Date c_entry_date;

	public Date c_change_date;

	public Character c_status_cd;

	public String valuetype_cd;

	public String getC_table_cd() {
		return c_table_cd;
	}

	public void setC_table_cd(String c_table_cd) {
		this.c_table_cd = c_table_cd;
	}

	public String getC_table_name() {
		return c_table_name;
	}

	public void setC_table_name(String c_table_name) {
		this.c_table_name = c_table_name;
	}

	public Character getC_protected_access() {
		return c_protected_access;
	}

	public void setC_protected_access(Character c_protected_access) {
		this.c_protected_access = c_protected_access;
	}

	public int getC_hlevel() {
		return c_hlevel;
	}

	public void setC_hlevel(int c_hlevel) {
		this.c_hlevel = c_hlevel;
	}

	public String getC_fullname() {
		return c_fullname;
	}

	public void setC_fullname(String c_fullname) {
		this.c_fullname = c_fullname;
	}

	public String getC_name() {
		return c_name;
	}

	public void setC_name(String c_name) {
		this.c_name = c_name;
	}

	public char getC_synonym_cd() {
		return c_synonym_cd;
	}

	public void setC_synonym_cd(char c_synonym_cd) {
		this.c_synonym_cd = c_synonym_cd;
	}

	public String getC_visualattributes() {
		return c_visualattributes;
	}

	public void setC_visualattributes(String c_visualattributes) {
		this.c_visualattributes = c_visualattributes;
	}

	public Integer getC_totalnum() {
		return c_totalnum;
	}

	public void setC_totalnum(Integer c_totalnum) {
		this.c_totalnum = c_totalnum;
	}

	public String getC_basecode() {
		return c_basecode;
	}

	public void setC_basecode(String c_basecode) {
		this.c_basecode = c_basecode;
	}

	public String getC_metadataxml() {
		return c_metadataxml;
	}

	public void setC_metadataxml(String c_metadataxml) {
		this.c_metadataxml = c_metadataxml;
	}

	public String getC_facttablecolumn() {
		return c_facttablecolumn;
	}

	public void setC_facttablecolumn(String c_facttablecolumn) {
		this.c_facttablecolumn = c_facttablecolumn;
	}

	public String getC_dimtablename() {
		return c_dimtablename;
	}

	public void setC_dimtablename(String c_dimtablename) {
		this.c_dimtablename = c_dimtablename;
	}

	public String getC_columnname() {
		return c_columnname;
	}

	public void setC_columnname(String c_columnname) {
		this.c_columnname = c_columnname;
	}

	public String getC_columndatatype() {
		return c_columndatatype;
	}

	public void setC_columndatatype(String c_columndatatype) {
		this.c_columndatatype = c_columndatatype;
	}

	public String getC_operator() {
		return c_operator;
	}

	public void setC_operator(String c_operator) {
		this.c_operator = c_operator;
	}

	public String getC_dimcode() {
		return c_dimcode;
	}

	public void setC_dimcode(String c_dimcode) {
		this.c_dimcode = c_dimcode;
	}

	public String getC_comment() {
		return c_comment;
	}

	public void setC_comment(String c_comment) {
		this.c_comment = c_comment;
	}

	public String getC_tooltip() {
		return c_tooltip;
	}

	public void setC_tooltip(String c_tooltip) {
		this.c_tooltip = c_tooltip;
	}

	public Date getC_entry_date() {
		return c_entry_date;
	}

	public void setC_entry_date(Date c_entry_date) {
		this.c_entry_date = c_entry_date;
	}

	public Date getC_change_date() {
		return c_change_date;
	}

	public void setC_change_date(Date c_change_date) {
		this.c_change_date = c_change_date;
	}

	public Character getC_status_cd() {
		return c_status_cd;
	}

	public void setC_status_cd(Character c_status_cd) {
		this.c_status_cd = c_status_cd;
	}

	public String getValuetype_cd() {
		return valuetype_cd;
	}

	public void setValuetype_cd(String valuetype_cd) {
		this.valuetype_cd = valuetype_cd;
	}
	
	

}
