package org.brisskit.i2b2.webapp.model;

// default package
// Generated 25-Jan-2015 14:11:32 by Hibernate Tools 3.2.0.beta8

import java.util.Date;

/**
 * TableAccessId generated by hbm2java
 */
public class TableAccessId implements java.io.Serializable {

	// Fields    

	private String CTableCd;

	private String CTableName;

	private Character CProtectedAccess;

	private int CHlevel;

	private String CFullname;

	private String CName;

	private char CSynonymCd;

	private String CVisualattributes;

	private Integer CTotalnum;

	private String CBasecode;

	private String CMetadataxml;

	private String CFacttablecolumn;

	private String CDimtablename;

	private String CColumnname;

	private String CColumndatatype;

	private String COperator;

	private String CDimcode;

	private String CComment;

	private String CTooltip;

	private Date CEntryDate;

	private Date CChangeDate;

	private Character CStatusCd;

	private String valuetypeCd;

	// Constructors

	/** default constructor */
	public TableAccessId() {
	}

	/** minimal constructor */
	public TableAccessId(String CTableCd, String CTableName, int CHlevel,
			String CFullname, String CName, char CSynonymCd,
			String CVisualattributes, String CFacttablecolumn,
			String CDimtablename, String CColumnname, String CColumndatatype,
			String COperator, String CDimcode) {
		this.CTableCd = CTableCd;
		this.CTableName = CTableName;
		this.CHlevel = CHlevel;
		this.CFullname = CFullname;
		this.CName = CName;
		this.CSynonymCd = CSynonymCd;
		this.CVisualattributes = CVisualattributes;
		this.CFacttablecolumn = CFacttablecolumn;
		this.CDimtablename = CDimtablename;
		this.CColumnname = CColumnname;
		this.CColumndatatype = CColumndatatype;
		this.COperator = COperator;
		this.CDimcode = CDimcode;
	}

	/** full constructor */
	public TableAccessId(String CTableCd, String CTableName,
			Character CProtectedAccess, int CHlevel, String CFullname,
			String CName, char CSynonymCd, String CVisualattributes,
			Integer CTotalnum, String CBasecode, String CMetadataxml,
			String CFacttablecolumn, String CDimtablename, String CColumnname,
			String CColumndatatype, String COperator, String CDimcode,
			String CComment, String CTooltip, Date CEntryDate,
			Date CChangeDate, Character CStatusCd, String valuetypeCd) {
		this.CTableCd = CTableCd;
		this.CTableName = CTableName;
		this.CProtectedAccess = CProtectedAccess;
		this.CHlevel = CHlevel;
		this.CFullname = CFullname;
		this.CName = CName;
		this.CSynonymCd = CSynonymCd;
		this.CVisualattributes = CVisualattributes;
		this.CTotalnum = CTotalnum;
		this.CBasecode = CBasecode;
		this.CMetadataxml = CMetadataxml;
		this.CFacttablecolumn = CFacttablecolumn;
		this.CDimtablename = CDimtablename;
		this.CColumnname = CColumnname;
		this.CColumndatatype = CColumndatatype;
		this.COperator = COperator;
		this.CDimcode = CDimcode;
		this.CComment = CComment;
		this.CTooltip = CTooltip;
		this.CEntryDate = CEntryDate;
		this.CChangeDate = CChangeDate;
		this.CStatusCd = CStatusCd;
		this.valuetypeCd = valuetypeCd;
	}

	// Property accessors
	public String getCTableCd() {
		return this.CTableCd;
	}

	public void setCTableCd(String CTableCd) {
		this.CTableCd = CTableCd;
	}

	public String getCTableName() {
		return this.CTableName;
	}

	public void setCTableName(String CTableName) {
		this.CTableName = CTableName;
	}

	public Character getCProtectedAccess() {
		return this.CProtectedAccess;
	}

	public void setCProtectedAccess(Character CProtectedAccess) {
		this.CProtectedAccess = CProtectedAccess;
	}

	public int getCHlevel() {
		return this.CHlevel;
	}

	public void setCHlevel(int CHlevel) {
		this.CHlevel = CHlevel;
	}

	public String getCFullname() {
		return this.CFullname;
	}

	public void setCFullname(String CFullname) {
		this.CFullname = CFullname;
	}

	public String getCName() {
		return this.CName;
	}

	public void setCName(String CName) {
		this.CName = CName;
	}

	public char getCSynonymCd() {
		return this.CSynonymCd;
	}

	public void setCSynonymCd(char CSynonymCd) {
		this.CSynonymCd = CSynonymCd;
	}

	public String getCVisualattributes() {
		return this.CVisualattributes;
	}

	public void setCVisualattributes(String CVisualattributes) {
		this.CVisualattributes = CVisualattributes;
	}

	public Integer getCTotalnum() {
		return this.CTotalnum;
	}

	public void setCTotalnum(Integer CTotalnum) {
		this.CTotalnum = CTotalnum;
	}

	public String getCBasecode() {
		return this.CBasecode;
	}

	public void setCBasecode(String CBasecode) {
		this.CBasecode = CBasecode;
	}

	public String getCMetadataxml() {
		return this.CMetadataxml;
	}

	public void setCMetadataxml(String CMetadataxml) {
		this.CMetadataxml = CMetadataxml;
	}

	public String getCFacttablecolumn() {
		return this.CFacttablecolumn;
	}

	public void setCFacttablecolumn(String CFacttablecolumn) {
		this.CFacttablecolumn = CFacttablecolumn;
	}

	public String getCDimtablename() {
		return this.CDimtablename;
	}

	public void setCDimtablename(String CDimtablename) {
		this.CDimtablename = CDimtablename;
	}

	public String getCColumnname() {
		return this.CColumnname;
	}

	public void setCColumnname(String CColumnname) {
		this.CColumnname = CColumnname;
	}

	public String getCColumndatatype() {
		return this.CColumndatatype;
	}

	public void setCColumndatatype(String CColumndatatype) {
		this.CColumndatatype = CColumndatatype;
	}

	public String getCOperator() {
		return this.COperator;
	}

	public void setCOperator(String COperator) {
		this.COperator = COperator;
	}

	public String getCDimcode() {
		return this.CDimcode;
	}

	public void setCDimcode(String CDimcode) {
		this.CDimcode = CDimcode;
	}

	public String getCComment() {
		return this.CComment;
	}

	public void setCComment(String CComment) {
		this.CComment = CComment;
	}

	public String getCTooltip() {
		return this.CTooltip;
	}

	public void setCTooltip(String CTooltip) {
		this.CTooltip = CTooltip;
	}

	public Date getCEntryDate() {
		return this.CEntryDate;
	}

	public void setCEntryDate(Date CEntryDate) {
		this.CEntryDate = CEntryDate;
	}

	public Date getCChangeDate() {
		return this.CChangeDate;
	}

	public void setCChangeDate(Date CChangeDate) {
		this.CChangeDate = CChangeDate;
	}

	public Character getCStatusCd() {
		return this.CStatusCd;
	}

	public void setCStatusCd(Character CStatusCd) {
		this.CStatusCd = CStatusCd;
	}

	public String getValuetypeCd() {
		return this.valuetypeCd;
	}

	public void setValuetypeCd(String valuetypeCd) {
		this.valuetypeCd = valuetypeCd;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TableAccessId))
			return false;
		TableAccessId castOther = (TableAccessId) other;

		return ((this.getCTableCd() == castOther.getCTableCd()) || (this
				.getCTableCd() != null
				&& castOther.getCTableCd() != null && this.getCTableCd()
				.equals(castOther.getCTableCd())))
				&& ((this.getCTableName() == castOther.getCTableName()) || (this
						.getCTableName() != null
						&& castOther.getCTableName() != null && this
						.getCTableName().equals(castOther.getCTableName())))
				&& ((this.getCProtectedAccess() == castOther
						.getCProtectedAccess()) || (this.getCProtectedAccess() != null
						&& castOther.getCProtectedAccess() != null && this
						.getCProtectedAccess().equals(
								castOther.getCProtectedAccess())))
				&& (this.getCHlevel() == castOther.getCHlevel())
				&& ((this.getCFullname() == castOther.getCFullname()) || (this
						.getCFullname() != null
						&& castOther.getCFullname() != null && this
						.getCFullname().equals(castOther.getCFullname())))
				&& ((this.getCName() == castOther.getCName()) || (this
						.getCName() != null
						&& castOther.getCName() != null && this.getCName()
						.equals(castOther.getCName())))
				&& (this.getCSynonymCd() == castOther.getCSynonymCd())
				&& ((this.getCVisualattributes() == castOther
						.getCVisualattributes()) || (this
						.getCVisualattributes() != null
						&& castOther.getCVisualattributes() != null && this
						.getCVisualattributes().equals(
								castOther.getCVisualattributes())))
				&& ((this.getCTotalnum() == castOther.getCTotalnum()) || (this
						.getCTotalnum() != null
						&& castOther.getCTotalnum() != null && this
						.getCTotalnum().equals(castOther.getCTotalnum())))
				&& ((this.getCBasecode() == castOther.getCBasecode()) || (this
						.getCBasecode() != null
						&& castOther.getCBasecode() != null && this
						.getCBasecode().equals(castOther.getCBasecode())))
				&& ((this.getCMetadataxml() == castOther.getCMetadataxml()) || (this
						.getCMetadataxml() != null
						&& castOther.getCMetadataxml() != null && this
						.getCMetadataxml().equals(castOther.getCMetadataxml())))
				&& ((this.getCFacttablecolumn() == castOther
						.getCFacttablecolumn()) || (this.getCFacttablecolumn() != null
						&& castOther.getCFacttablecolumn() != null && this
						.getCFacttablecolumn().equals(
								castOther.getCFacttablecolumn())))
				&& ((this.getCDimtablename() == castOther.getCDimtablename()) || (this
						.getCDimtablename() != null
						&& castOther.getCDimtablename() != null && this
						.getCDimtablename()
						.equals(castOther.getCDimtablename())))
				&& ((this.getCColumnname() == castOther.getCColumnname()) || (this
						.getCColumnname() != null
						&& castOther.getCColumnname() != null && this
						.getCColumnname().equals(castOther.getCColumnname())))
				&& ((this.getCColumndatatype() == castOther
						.getCColumndatatype()) || (this.getCColumndatatype() != null
						&& castOther.getCColumndatatype() != null && this
						.getCColumndatatype().equals(
								castOther.getCColumndatatype())))
				&& ((this.getCOperator() == castOther.getCOperator()) || (this
						.getCOperator() != null
						&& castOther.getCOperator() != null && this
						.getCOperator().equals(castOther.getCOperator())))
				&& ((this.getCDimcode() == castOther.getCDimcode()) || (this
						.getCDimcode() != null
						&& castOther.getCDimcode() != null && this
						.getCDimcode().equals(castOther.getCDimcode())))
				&& ((this.getCComment() == castOther.getCComment()) || (this
						.getCComment() != null
						&& castOther.getCComment() != null && this
						.getCComment().equals(castOther.getCComment())))
				&& ((this.getCTooltip() == castOther.getCTooltip()) || (this
						.getCTooltip() != null
						&& castOther.getCTooltip() != null && this
						.getCTooltip().equals(castOther.getCTooltip())))
				&& ((this.getCEntryDate() == castOther.getCEntryDate()) || (this
						.getCEntryDate() != null
						&& castOther.getCEntryDate() != null && this
						.getCEntryDate().equals(castOther.getCEntryDate())))
				&& ((this.getCChangeDate() == castOther.getCChangeDate()) || (this
						.getCChangeDate() != null
						&& castOther.getCChangeDate() != null && this
						.getCChangeDate().equals(castOther.getCChangeDate())))
				&& ((this.getCStatusCd() == castOther.getCStatusCd()) || (this
						.getCStatusCd() != null
						&& castOther.getCStatusCd() != null && this
						.getCStatusCd().equals(castOther.getCStatusCd())))
				&& ((this.getValuetypeCd() == castOther.getValuetypeCd()) || (this
						.getValuetypeCd() != null
						&& castOther.getValuetypeCd() != null && this
						.getValuetypeCd().equals(castOther.getValuetypeCd())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getCTableCd() == null ? 0 : this.getCTableCd().hashCode());
		result = 37
				* result
				+ (getCTableName() == null ? 0 : this.getCTableName()
						.hashCode());
		result = 37
				* result
				+ (getCProtectedAccess() == null ? 0 : this
						.getCProtectedAccess().hashCode());
		result = 37 * result + this.getCHlevel();
		result = 37 * result
				+ (getCFullname() == null ? 0 : this.getCFullname().hashCode());
		result = 37 * result
				+ (getCName() == null ? 0 : this.getCName().hashCode());
		result = 37 * result + this.getCSynonymCd();
		result = 37
				* result
				+ (getCVisualattributes() == null ? 0 : this
						.getCVisualattributes().hashCode());
		result = 37 * result
				+ (getCTotalnum() == null ? 0 : this.getCTotalnum().hashCode());
		result = 37 * result
				+ (getCBasecode() == null ? 0 : this.getCBasecode().hashCode());
		result = 37
				* result
				+ (getCMetadataxml() == null ? 0 : this.getCMetadataxml()
						.hashCode());
		result = 37
				* result
				+ (getCFacttablecolumn() == null ? 0 : this
						.getCFacttablecolumn().hashCode());
		result = 37
				* result
				+ (getCDimtablename() == null ? 0 : this.getCDimtablename()
						.hashCode());
		result = 37
				* result
				+ (getCColumnname() == null ? 0 : this.getCColumnname()
						.hashCode());
		result = 37
				* result
				+ (getCColumndatatype() == null ? 0 : this.getCColumndatatype()
						.hashCode());
		result = 37 * result
				+ (getCOperator() == null ? 0 : this.getCOperator().hashCode());
		result = 37 * result
				+ (getCDimcode() == null ? 0 : this.getCDimcode().hashCode());
		result = 37 * result
				+ (getCComment() == null ? 0 : this.getCComment().hashCode());
		result = 37 * result
				+ (getCTooltip() == null ? 0 : this.getCTooltip().hashCode());
		result = 37
				* result
				+ (getCEntryDate() == null ? 0 : this.getCEntryDate()
						.hashCode());
		result = 37
				* result
				+ (getCChangeDate() == null ? 0 : this.getCChangeDate()
						.hashCode());
		result = 37 * result
				+ (getCStatusCd() == null ? 0 : this.getCStatusCd().hashCode());
		result = 37
				* result
				+ (getValuetypeCd() == null ? 0 : this.getValuetypeCd()
						.hashCode());
		return result;
	}

}
